[workspace]
members = [
    "crates/optid",
    "crates/optctl",
    "crates/rushbench",
    "crates/rush_collect",
    "crates/rush_telemetry",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/Nan0pk/Rush-linux"
rust-version = "1.78"
version = "0.4.0-alpha.1"
