[advisories]
version = 2
ignore = []

[licenses]
version = 2
confidence-threshold = 0.8
allow = [
    "Apache-2.0",
    "MIT",
    "BSD-3-Clause",
    "Unicode-DFS-2016",
]

[bans]
version = 2
deny = []
skip = []
skip-tree = []

[sources]
version = 2
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
