[Distribution]
Distribution=arch

[Output]
Format=disk
ImageId=disk
OutputDirectory=../build

[Content]
Bootable=yes
Packages=
    base
    linux
    systemd-sysvcompat
    zram-generator
    nftables
    dbus
    bash
Autologin=yes
KernelCommandLine=systemd.unified_cgroup_hierarchy=1 cgroup_no_v1=all psi=1 zswap.enabled=1 root=/dev/vda2 rw console=ttyS0,115200 systemd.firstboot=no efi=debug
