[package]
name = "systemd"
kind = "base"

[build]
features = [
  "unified-cgroup-hierarchy",
  "ukify",
  "systemd-boot",
  "sysupdate",
  "oomd",
  "networkd",
  "resolved",
]

[policy]
default_init = true
dual_init_supported = false
cgroup_v1_supported = false

