#!/usr/bin/env python3
"""
generate-fixtures.py — generate the 'good' testOS cloud-safe fixture using
real repo data (current commit, VERSION, computed SHA-256s).

Run this from the repo root after checking out a new commit to refresh the
fixture. The fixture is intentionally NOT committed with hardcoded SHAs
because they would go stale on every commit; instead, the 'good' fixture
is regenerated on demand and the cloud-safe regression tests
(tools/test-cloud-safe-livedev.py) build fixtures dynamically in temp
directories for the actual assertions.

Usage:
  python3 tools/test-fixtures/testos-cloud-safe/generate-fixtures.py
"""

from __future__ import annotations

import datetime as dt
import hashlib
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
FIXTURE_DIR = Path(__file__).resolve().parent / "good"


def _git_head() -> str:
    r = subprocess.run(
        ["git", "-C", str(ROOT), "rev-parse", "HEAD"],
        capture_output=True, text=True, timeout=5,
    )
    return r.stdout.strip()


def _version() -> str:
    return (ROOT / "VERSION").read_text().strip()


def _sha256(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()


def _now_iso() -> str:
    return dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def main() -> int:
    FIXTURE_DIR.mkdir(parents=True, exist_ok=True)
    head = _git_head()
    version = _version()
    bench_list = (ROOT / "testos" / "bench-list.toml").read_bytes()
    catalog_sha = _sha256(bench_list)
    plan_bytes = json.dumps({
        "schema_version": 1, "plan_kind": "rush-autopilot-plan",
        "generated_at": _now_iso(), "source_version": version,
        "source_commit": head, "dry_run": False,
        "campaign_scope": "baseline-only",
        "hardware_slot": "laptop", "slot_confidence": "high",
        "ambiguities": [], "open_criteria": [],
        "existing_evidence": [], "steps": [], "repo_root": ".",
    }).encode()
    plan_sha = _sha256(plan_bytes)
    image_digest = f"sha256:{'a' * 64}"  # placeholder image digest for the fixture

    intent = {
        "schema_version": 1,
        "intent_kind": "testos-run-intent",
        "run_id": "fixture-good-0001",
        "source_commit": head,
        "source_version": version,
        "testos_version": version,
        "testos_image_digest": image_digest,
        "plan_sha256": plan_sha,
        "benchmark_catalog_sha256": catalog_sha,
        "generated_at": _now_iso(),
        "dry_run": False,
        "checkpoint_nonce": "fixture-ckpt-0001-abcd",
        "campaign_id": "fixture-campaign-0001",
    }
    intent_raw = json.dumps(intent, indent=2).encode()
    intent_sha = _sha256(intent_raw)

    result = {
        "schema_version": 1,
        "bench_id": "shell-pass",
        "bench_name": "fixture shell pass",
        "scenario": "server-throughput",
        "status": "pass",
        "started_at": _now_iso(),
        "finished_at": _now_iso(),
        "elapsed_seconds": 0.01,
        "host": {"fingerprint": "fixture-host-0001"},
    }

    manifest = {
        "schema_version": 1,
        "started_at": _now_iso(),
        "finished_at": _now_iso(),
        "mode": "all",
        "attempted": ["shell-pass"],
        "passed": ["shell-pass"],
        "failed": [],
        "skipped": [],
        "host": {"fingerprint": "fixture-host-0001"},
        "testos_version": version,
        "provenance": {
            "run_id": intent["run_id"],
            "source_commit": head,
            "source_version": version,
            "testos_version": version,
            "testos_image_digest": image_digest,
            "plan_sha256": plan_sha,
            "benchmark_catalog_sha256": catalog_sha,
            "intent_generated_at": intent["generated_at"],
            "intent_dry_run": False,
            "checkpoint_nonce": intent["checkpoint_nonce"],
            "intent_sha256": intent_sha,
            "campaign_id": intent["campaign_id"],
        },
    }

    (FIXTURE_DIR / "run-intent.json").write_bytes(intent_raw)
    (FIXTURE_DIR / "plan.json").write_bytes(plan_bytes)
    (FIXTURE_DIR / "bench-list.toml").write_bytes(bench_list)
    (FIXTURE_DIR / "manifest.json").write_text(json.dumps(manifest, indent=2))
    (FIXTURE_DIR / "shell-pass.json").write_text(json.dumps(result, indent=2))
    (FIXTURE_DIR / "source-sha.txt").write_text(head[:12])
    # Generate result-hashes.json (mandatory).
    result_raw = (FIXTURE_DIR / "shell-pass.json").read_bytes()
    (FIXTURE_DIR / "result-hashes.json").write_text(json.dumps({
        "shell-pass.json": _sha256(result_raw),
    }))
    (FIXTURE_DIR / "expected.json").write_text(json.dumps({
        "description": "Valid testOS cloud-safe bundle — all checks pass. "
                       "Regenerated by generate-fixtures.py against the current commit.",
        "expect_pass": True,
        "expect_errors": [],
    }, indent=2))
    print(f"Generated 'good' fixture at {FIXTURE_DIR} (commit {head[:12]}, version {version})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
