//! F3 — Versioned observation, decision, and action-outcome envelopes.
//!
//! This module defines the versioned cross-domain state model that the
//! OPTID-COMPLETION-PLAN F3 package calls for. Before F3, `Snapshot`,
//! `Decision`, actions, skip reasons, and status surfaces were separate
//! structures without a versioned envelope — `optctl`, logs, tests, and
//! future telemetry each had to re-derive what happened from ad-hoc
//! text rendering. F3 introduces typed, versioned envelopes that wrap
//! the existing types without changing their semantics.
//!
//! ## Schema versioning
//!
//! All envelopes carry `schema_version = 1` (the initial version after
//! F3). Forward compatibility is enforced via serde defaults: unknown
//! fields are ignored on deserialization (so a v2 reader can consume
//! v1 JSON), and optional fields default to `None`/`Unknown` when
//! absent. The version is bumped only on breaking changes (renamed
//! fields, removed variants, changed semantics).
//!
//! ## Types
//!
//! - [`ObservationEnvelope`] — wraps a `Snapshot` summary + per-domain
//!   observations. One per control-loop iteration.
//! - [`DesiredState`] — the complete desired state per domain, tracked
//!   by the reconciler (F4). Includes baseline, desired, last
//!   attempted, and last confirmed applied values.
//! - [`GateOutcome`] — whether actuation is permitted for a domain,
//!   with a typed deny reason.
//! - [`ApplyOutcome`] — the result of applying an `Action`: applied,
//!   skipped, failed, drifted, or restored.
//! - [`RestoreOutcome`] — the result of restoring a domain on
//!   transition: restored, stabilized, relinquished, or failed.
//!
//! ## Design rules (F3 plan)
//!
//! 1. **No source path leaks.** Envelopes carry domain names and
//!    human-readable descriptions, never `file!()` / `line!()` / raw
//!    sysfs paths. The diagnostic surface is the permitted boundary.
//! 2. **Unsupported ≠ skipped ≠ failed.** These are distinct enum
//!    variants, not string suffixes. A domain that is unsupported
//!    (e.g. no backlight) is not the same as one that was skipped
//!    (e.g. dry-run) or one that failed (e.g. EBUSY).
//! 3. **Timestamps are Unix seconds.** Provenance is a string source
//!    identifier (e.g. `"sysfs"`, `"procfs"`, `"config"`).
//! 4. **Correlation IDs.** Every envelope carries a correlation ID so
//!    logs, status, and future telemetry can cross-reference a single
//!    control-loop iteration.
//! 5. **No decision changes.** F3 does not alter `Policy::decide_resolved`
//!    or `Actuator::apply`. It wraps their outputs in versioned types.
//!
//! Note: the envelope types are defined here but not yet wired into the
//! main loop or `Decision::render`. F4 (reconciler) and later packages
//! consume them. The `#[allow(dead_code)]` below suppresses warnings
//! until the types are referenced by production code.

#![allow(dead_code)]

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

use crate::policy::{Domain, DomainMode};

/// Current envelope schema version. Bumped only on breaking changes.
pub(crate) const ENVELOPE_SCHEMA_VERSION: u32 = 1;

/// A UUID-style correlation identifier for one control-loop iteration.
/// Generated by the main loop and threaded through every envelope so
/// logs, status, and telemetry can cross-reference. Empty string when
/// not applicable (e.g. ad-hoc test construction).
pub(crate) type CorrelationId = String;

// ─────────────────────────────────────────────────────────────────────
// Support status
// ─────────────────────────────────────────────────────────────────────

/// Whether a domain is supported on the current hardware. Distinct from
/// `GateOutcome` (which describes whether actuation is permitted) and
/// `ApplyResult` (which describes what happened when actuation was
/// attempted).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub(crate) enum SupportStatus {
    /// The domain's kernel interface is present and readable.
    Supported,
    /// The domain's kernel interface is absent (e.g. no backlight device).
    Unsupported { reason: String },
    /// The domain's support could not be determined (e.g. read error).
    #[default]
    Unknown,
}

// ─────────────────────────────────────────────────────────────────────
// Gate outcome
// ─────────────────────────────────────────────────────────────────────

/// Whether actuation is permitted for a domain, with a typed deny
/// reason. This is the F3 rendering of F1's `EffectiveConfig::allows_actuation`
/// plus the existing `--apply` / allowlist / contract gates.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub(crate) enum GateOutcome {
    /// All gates passed; the domain may actuate.
    Permitted,
    /// A gate denied actuation. The variant identifies which gate.
    Denied { reason: DenyReason },
    /// The gate was not evaluated (e.g. the domain produced no action
    /// this cycle, so the gate was not consulted).
    NotEvaluated,
}

/// Typed deny reason. Distinct from `ApplyResult::Skipped` (which
/// describes what happened at actuation time, after the gate passed).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub(crate) enum DenyReason {
    /// `--apply` was not set (dry-run).
    DryRun,
    /// F1 domain mode is `Off`.
    DomainOff,
    /// F1 domain mode is `Observe`.
    DomainObserve,
    /// The hardware allowlist denied the device.
    AllowlistDeny { hwid: String, detail: String },
    /// The responsiveness contract floor was not met.
    ContractFloor { class: String, floor: String },
    /// The device HWID could not be resolved.
    UnresolvedHwid,
}

impl GateOutcome {
    /// Build a `GateOutcome` from F1's `DomainMode`. `Actuate` →
    /// `Permitted` (the domain gate passed; other gates still apply).
    /// `Off` → `Denied(DomainOff)`. `Observe` → `Denied(DomainObserve)`.
    pub(crate) fn from_domain_mode(mode: DomainMode) -> Self {
        match mode {
            DomainMode::Actuate => GateOutcome::Permitted,
            DomainMode::Off => GateOutcome::Denied {
                reason: DenyReason::DomainOff,
            },
            DomainMode::Observe => GateOutcome::Denied {
                reason: DenyReason::DomainObserve,
            },
        }
    }
}

// ─────────────────────────────────────────────────────────────────────
// Apply outcome
// ─────────────────────────────────────────────────────────────────────

/// The result of applying an `Action`. Produced by the actuator and
/// consumed by the reconciler (F4) and the status surface.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct ApplyOutcome {
    /// Unix-seconds timestamp of the apply attempt.
    pub timestamp: u64,
    /// Human-readable action description (from `Action::describe()`).
    /// Never a raw sysfs path — the diagnostic surface is the boundary.
    pub action: String,
    /// The typed result.
    pub result: ApplyResult,
    /// Correlation ID of the control-loop iteration that produced this
    /// apply.
    pub correlation_id: CorrelationId,
}

/// The typed result of an apply attempt. `Unsupported`, `Skipped`, and
/// `Failed` are distinct variants — the F3 plan requires they not be
/// conflated.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub(crate) enum ApplyResult {
    /// The write landed successfully.
    Applied { written_value: String },
    /// The action was skipped (e.g. dry-run, allowlist denial, redundant
    /// write). The reason explains why.
    Skipped { reason: String },
    /// The write failed (e.g. EBUSY, ENOENT, EACCES).
    Failed { error: String },
    /// The write landed, but a subsequent readback showed a different
    /// value — the device drifted.
    Drifted { expected: String, actual: String },
    /// A previous write was restored (reverted) to its journaled original.
    Restored { original: String },
}

// ─────────────────────────────────────────────────────────────────────
// Restore outcome
// ─────────────────────────────────────────────────────────────────────

/// The result of restoring a domain on a transition (AC attach,
/// workload-class change, config reload, device removal, domain
/// disable). Produced by the reconciler (F4).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct RestoreOutcome {
    /// Unix-seconds timestamp of the restore attempt.
    pub timestamp: u64,
    /// Domain name (matches `Domain::as_str()`).
    pub domain: String,
    /// The typed result.
    pub result: RestoreResult,
    /// Correlation ID of the transition that triggered this restore.
    pub correlation_id: CorrelationId,
}

/// The typed result of a restore attempt. `Restored` (exact original)
/// is distinct from `Stabilized` (conservative fallback) per the D2
/// amendment's "rollback and stabilization are distinct" invariant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub(crate) enum RestoreResult {
    /// The exact captured original value was restored.
    Restored { original: String },
    /// Exact restoration was impossible; a conservative fallback was
    /// applied instead.
    Stabilized { fallback: String, reason: String },
    /// optid relinquished ownership (another program changed the value
    /// after optid's last applied value; optid will not fight it).
    Relinquished { reason: String },
    /// The restore failed.
    Failed { error: String },
}

// ─────────────────────────────────────────────────────────────────────
// Desired state
// ─────────────────────────────────────────────────────────────────────

/// The complete desired state per domain, tracked by the reconciler
/// (F4). This is the F3 plan's "policy returns a complete desired state
/// per domain" contract — no setting remains active merely because
/// policy stopped mentioning it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct DesiredState {
    /// Unix-seconds timestamp of this desired-state snapshot.
    pub timestamp: u64,
    /// Correlation ID of the control-loop iteration.
    pub correlation_id: CorrelationId,
    /// Per-domain desired states, in `Domain::all()` order.
    pub domains: Vec<DesiredDomainState>,
}

/// The desired state for one domain.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct DesiredDomainState {
    /// Domain name (matches `Domain::as_str()`).
    pub domain: String,
    /// The value optid wants to set, or `None` if optid wants the
    /// domain to remain at its baseline (no active write).
    pub desired_value: Option<String>,
    /// The baseline value optid captured at startup or last transition.
    /// This is what optid restores to when the domain is disabled or
    /// the workload class changes.
    pub baseline_value: Option<String>,
    /// The last value optid attempted to write. `None` if no write has
    /// been attempted since the last transition.
    pub last_attempted: Option<String>,
    /// The last value optid confirmed via readback. `None` if no write
    /// has been confirmed. Distinct from `last_attempted` because a
    /// write may fail or drift.
    pub last_confirmed: Option<String>,
    /// Who owns the domain right now.
    pub ownership: Ownership,
}

/// Ownership state for a domain.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub(crate) enum Ownership {
    /// optid owns the domain and may write to it.
    Optid,
    /// Another program changed the value after optid's last applied
    /// value. optid relinquishes ownership and will not fight it.
    External { reason: String },
    /// The domain is not currently owned by optid (e.g. it was never
    /// actuated, or it was explicitly disabled).
    Unowned,
}

impl DesiredState {
    /// Build an empty `DesiredState` (all domains `Unowned`, no
    /// desired/baseline/attempted/confirmed values). Used at startup
    /// before the first policy decision.
    pub(crate) fn empty(timestamp: u64, correlation_id: CorrelationId) -> Self {
        let domains = Domain::all()
            .iter()
            .map(|d| DesiredDomainState {
                domain: d.as_str().to_string(),
                desired_value: None,
                baseline_value: None,
                last_attempted: None,
                last_confirmed: None,
                ownership: Ownership::Unowned,
            })
            .collect();
        Self {
            timestamp,
            correlation_id,
            domains,
        }
    }

    /// Look up the desired state for a specific domain.
    pub(crate) fn for_domain(&self, domain: Domain) -> Option<&DesiredDomainState> {
        self.domains.iter().find(|d| d.domain == domain.as_str())
    }

    /// Mutably look up the desired state for a specific domain.
    pub(crate) fn for_domain_mut(&mut self, domain: Domain) -> Option<&mut DesiredDomainState> {
        self.domains
            .iter_mut()
            .find(|d| d.domain == domain.as_str())
    }
}

// ─────────────────────────────────────────────────────────────────────
// Observation envelope
// ─────────────────────────────────────────────────────────────────────

/// A versioned summary of one control-loop iteration. Wraps the
/// `Snapshot` summary + per-domain observations (support status, gate
/// outcome, last apply outcome). One envelope per iteration.
///
/// This is the F3 plan's "versioned cross-domain envelope" that
/// `optctl`, logs, tests, and future telemetry consume.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub(crate) struct ObservationEnvelope {
    /// Schema version. Currently 1. Bumped only on breaking changes.
    pub schema_version: u32,
    /// Unix-seconds timestamp of the observation.
    pub timestamp: u64,
    /// Correlation ID for cross-referencing logs and telemetry.
    pub correlation_id: CorrelationId,
    /// Summary of the `Snapshot` (on_ac, battery_pct, thermal, PSI, etc.).
    pub snapshot: SnapshotSummary,
    /// Per-domain observations, in `Domain::all()` order.
    pub domains: Vec<DomainObservation>,
}

/// A summary of the `Snapshot` — the fields that matter for diagnostics
/// and telemetry. Does not include raw sysfs paths.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub(crate) struct SnapshotSummary {
    pub on_ac: Option<bool>,
    pub battery_pct: Option<u8>,
    pub thermal_c: Option<f32>,
    pub loadavg_1: Option<f32>,
    pub cpu_pressure_avg10: Option<f32>,
    pub memory_pressure_avg10: Option<f32>,
    pub io_pressure_avg10: Option<f32>,
    pub zram_swap_active: bool,
    pub is_vm_guest: bool,
    /// The resolved workload class.
    pub workload_class: String,
    /// The resolved mode.
    pub mode: String,
}

/// Per-domain observation within an `ObservationEnvelope`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct DomainObservation {
    /// Domain name (matches `Domain::as_str()`).
    pub domain: String,
    /// Whether the domain's kernel interface is present.
    pub support: SupportStatus,
    /// The effective runtime mode (from F1's `EffectiveConfig`).
    pub mode: DomainMode,
    /// Whether actuation is permitted this cycle.
    pub gate: GateOutcome,
    /// The last apply outcome for this domain, if any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_apply: Option<ApplyOutcome>,
}

impl ObservationEnvelope {
    /// Build an envelope from a snapshot summary + per-domain
    /// observations. The caller provides the domain observations;
    /// this method wraps them with schema version and correlation ID.
    pub(crate) fn new(
        timestamp: u64,
        correlation_id: CorrelationId,
        snapshot: SnapshotSummary,
        domains: Vec<DomainObservation>,
    ) -> Self {
        Self {
            schema_version: ENVELOPE_SCHEMA_VERSION,
            timestamp,
            correlation_id,
            snapshot,
            domains,
        }
    }

    /// Serialize to a pretty-printed JSON string. Used by `optctl status`
    /// and the decisions log.
    pub(crate) fn to_json(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(self)
    }

    /// Deserialize from a JSON string. Unknown fields are ignored for
    /// forward compatibility.
    pub(crate) fn from_json(json: &str) -> Result<Self, serde_json::Error> {
        serde_json::from_str(json)
    }

    /// Look up the observation for a specific domain.
    pub(crate) fn for_domain(&self, domain: Domain) -> Option<&DomainObservation> {
        self.domains.iter().find(|d| d.domain == domain.as_str())
    }
}

// ─────────────────────────────────────────────────────────────────────
// Provenance tracking
// ─────────────────────────────────────────────────────────────────────

/// A provenance tag: where did a value come from? Used by the
/// reconciler (F4) to track whether a baseline was captured from
/// sysfs, config, or a previous apply.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub(crate) enum Provenance {
    /// Read from sysfs/procfs at startup.
    Sysfs,
    /// Read from procfs at startup.
    Procfs,
    /// Set by optid's config (policy.toml).
    Config,
    /// Written by optid in a previous apply.
    OptidApplied { correlation_id: CorrelationId },
    /// Captured from an external program (drift detected).
    External,
    /// Default value (no source).
    Default,
}

/// A value with provenance. Used by the reconciler to track not just
/// what the baseline is, but where it came from.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct ProvenancedValue {
    pub value: String,
    pub provenance: Provenance,
    /// Unix-seconds timestamp of when the value was captured.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub captured_at: Option<u64>,
}

// ─────────────────────────────────────────────────────────────────────
// Forward-compatibility: unknown-field tolerance
// ─────────────────────────────────────────────────────────────────────

/// A catch-all map for unknown fields. Serde will populate this with
/// any fields it doesn't recognize, so a v1 reader can consume v2 JSON
/// without failing. The fields are preserved on re-serialization, so
/// round-tripping is lossless.
///
/// This is intentionally a `HashMap<String, serde_json::Value>` rather
/// than a typed struct — the whole point is that the fields are
/// unknown to this version.
pub(crate) type UnknownFields = HashMap<String, serde_json::Value>;

// ─────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // ── Schema version ──────────────────────────────────────────────

    #[test]
    fn f3_schema_version_is_1() {
        assert_eq!(ENVELOPE_SCHEMA_VERSION, 1);
    }

    // ── GateOutcome ─────────────────────────────────────────────────

    #[test]
    fn f3_gate_outcome_from_domain_mode_actuate_is_permitted() {
        assert_eq!(
            GateOutcome::from_domain_mode(DomainMode::Actuate),
            GateOutcome::Permitted
        );
    }

    #[test]
    fn f3_gate_outcome_from_domain_mode_off_is_denied_domain_off() {
        assert_eq!(
            GateOutcome::from_domain_mode(DomainMode::Off),
            GateOutcome::Denied {
                reason: DenyReason::DomainOff
            }
        );
    }

    #[test]
    fn f3_gate_outcome_from_domain_mode_observe_is_denied_domain_observe() {
        assert_eq!(
            GateOutcome::from_domain_mode(DomainMode::Observe),
            GateOutcome::Denied {
                reason: DenyReason::DomainObserve
            }
        );
    }

    // ── ApplyResult: unsupported ≠ skipped ≠ failed ────────────────

    #[test]
    fn f3_apply_result_variants_are_distinct() {
        let applied = ApplyResult::Applied {
            written_value: "60".to_string(),
        };
        let skipped = ApplyResult::Skipped {
            reason: "dry-run".to_string(),
        };
        let failed = ApplyResult::Failed {
            error: "EBUSY".to_string(),
        };
        let drifted = ApplyResult::Drifted {
            expected: "60".to_string(),
            actual: "100".to_string(),
        };
        let restored = ApplyResult::Restored {
            original: "100".to_string(),
        };
        // All five variants are distinct.
        assert_ne!(applied, skipped);
        assert_ne!(applied, failed);
        assert_ne!(applied, drifted);
        assert_ne!(applied, restored);
        assert_ne!(skipped, failed);
        assert_ne!(skipped, drifted);
        assert_ne!(skipped, restored);
        assert_ne!(failed, drifted);
        assert_ne!(failed, restored);
        assert_ne!(drifted, restored);
    }

    // ── RestoreResult: restored ≠ stabilized ≠ relinquished ────────

    #[test]
    fn f3_restore_result_variants_are_distinct() {
        let restored = RestoreResult::Restored {
            original: "100".to_string(),
        };
        let stabilized = RestoreResult::Stabilized {
            fallback: "default".to_string(),
            reason: "original unreadable".to_string(),
        };
        let relinquished = RestoreResult::Relinquished {
            reason: "external change detected".to_string(),
        };
        let failed = RestoreResult::Failed {
            error: "EIO".to_string(),
        };
        assert_ne!(restored, stabilized);
        assert_ne!(restored, relinquished);
        assert_ne!(restored, failed);
        assert_ne!(stabilized, relinquished);
        assert_ne!(stabilized, failed);
        assert_ne!(relinquished, failed);
    }

    // ── DesiredState ────────────────────────────────────────────────

    #[test]
    fn f3_desired_state_empty_has_all_domains_unowned() {
        let ds = DesiredState::empty(1000, "corr-1".to_string());
        assert_eq!(ds.domains.len(), Domain::all().len());
        for d in &ds.domains {
            assert_eq!(d.ownership, Ownership::Unowned);
            assert!(d.desired_value.is_none());
            assert!(d.baseline_value.is_none());
            assert!(d.last_attempted.is_none());
            assert!(d.last_confirmed.is_none());
        }
    }

    #[test]
    fn f3_desired_state_for_domain_returns_correct_entry() {
        let ds = DesiredState::empty(1000, "corr-1".to_string());
        let entry = ds.for_domain(Domain::CpuEpp).unwrap();
        assert_eq!(entry.domain, "cpu_epp");
    }

    #[test]
    fn f3_desired_state_for_domain_mut_alls_update() {
        let mut ds = DesiredState::empty(1000, "corr-1".to_string());
        {
            let entry = ds.for_domain_mut(Domain::RuntimePm).unwrap();
            entry.desired_value = Some("auto".to_string());
            entry.ownership = Ownership::Optid;
        }
        let entry = ds.for_domain(Domain::RuntimePm).unwrap();
        assert_eq!(entry.desired_value, Some("auto".to_string()));
        assert_eq!(entry.ownership, Ownership::Optid);
    }

    // ── ObservationEnvelope serialization ──────────────────────────

    #[test]
    fn f3_envelope_round_trip_preserves_all_fields() {
        let envelope = ObservationEnvelope::new(
            1234567890,
            "corr-test-1".to_string(),
            SnapshotSummary {
                on_ac: Some(true),
                battery_pct: Some(80),
                thermal_c: Some(45.5),
                loadavg_1: Some(0.5),
                cpu_pressure_avg10: Some(1.0),
                memory_pressure_avg10: Some(2.0),
                io_pressure_avg10: Some(3.0),
                zram_swap_active: true,
                is_vm_guest: false,
                workload_class: "interactive".to_string(),
                mode: "balanced".to_string(),
            },
            vec![DomainObservation {
                domain: "cpu_epp".to_string(),
                support: SupportStatus::Supported,
                mode: DomainMode::Actuate,
                gate: GateOutcome::Permitted,
                last_apply: Some(ApplyOutcome {
                    timestamp: 1234567880,
                    action: "cpu.epp=performance".to_string(),
                    result: ApplyResult::Applied {
                        written_value: "performance".to_string(),
                    },
                    correlation_id: "corr-test-1".to_string(),
                }),
            }],
        );
        let json = envelope.to_json().unwrap();
        let restored = ObservationEnvelope::from_json(&json).unwrap();
        assert_eq!(envelope, restored);
    }

    #[test]
    fn f3_envelope_json_includes_schema_version() {
        let envelope = ObservationEnvelope::new(
            0,
            "corr".to_string(),
            SnapshotSummary {
                on_ac: None,
                battery_pct: None,
                thermal_c: None,
                loadavg_1: None,
                cpu_pressure_avg10: None,
                memory_pressure_avg10: None,
                io_pressure_avg10: None,
                zram_swap_active: false,
                is_vm_guest: false,
                workload_class: "idle".to_string(),
                mode: "auto".to_string(),
            },
            vec![],
        );
        let json = envelope.to_json().unwrap();
        assert!(
            json.contains("\"schema_version\": 1"),
            "JSON must include schema_version, got: {json}"
        );
    }

    // ── Forward compatibility: unknown fields ──────────────────────

    #[test]
    fn f3_envelope_tolerates_unknown_fields() {
        // A v2 JSON with an extra field that v1 doesn't know about.
        let json = r#"{
            "schema_version": 1,
            "timestamp": 100,
            "correlation_id": "corr-x",
            "snapshot": {
                "on_ac": true,
                "battery_pct": 50,
                "thermal_c": 40.0,
                "loadavg_1": 1.0,
                "cpu_pressure_avg10": 0.5,
                "memory_pressure_avg10": 0.5,
                "io_pressure_avg10": 0.5,
                "zram_swap_active": true,
                "is_vm_guest": false,
                "workload_class": "interactive",
                "mode": "balanced",
                "future_field": "v2-data"
            },
            "domains": [],
            "future_top_level": 42
        }"#;
        let result = ObservationEnvelope::from_json(json);
        assert!(
            result.is_ok(),
            "v1 reader must tolerate v2 unknown fields, got error: {:?}",
            result.err()
        );
        let envelope = result.unwrap();
        assert_eq!(envelope.timestamp, 100);
        assert_eq!(envelope.correlation_id, "corr-x");
    }

    #[test]
    fn f3_envelope_tolerates_missing_optional_fields() {
        // JSON missing last_apply (which is Option::None by default).
        // Uses snake_case enum representation (serde rename_all).
        let json = r#"{
            "schema_version": 1,
            "timestamp": 200,
            "correlation_id": "corr-y",
            "snapshot": {
                "on_ac": false,
                "battery_pct": null,
                "thermal_c": null,
                "loadavg_1": null,
                "cpu_pressure_avg10": null,
                "memory_pressure_avg10": null,
                "io_pressure_avg10": null,
                "zram_swap_active": false,
                "is_vm_guest": false,
                "workload_class": "idle",
                "mode": "battery"
            },
            "domains": [
                {
                    "domain": "runtime_pm",
                    "support": {"unsupported": {"reason": "no devices"}},
                    "mode": "off",
                    "gate": {"denied": {"reason": "domain_off"}}
                }
            ]
        }"#;
        let result = ObservationEnvelope::from_json(json);
        assert!(
            result.is_ok(),
            "must tolerate missing optional fields, got error: {:?}",
            result.err()
        );
        let envelope = result.unwrap();
        let dom = envelope.for_domain(Domain::RuntimePm).unwrap();
        assert!(
            dom.last_apply.is_none(),
            "missing last_apply must default to None"
        );
    }

    // ── No source path leaks ───────────────────────────────────────

    #[test]
    fn f3_envelope_json_contains_no_file_paths() {
        let envelope = ObservationEnvelope::new(
            0,
            "corr".to_string(),
            SnapshotSummary {
                on_ac: Some(true),
                battery_pct: Some(80),
                thermal_c: Some(45.0),
                loadavg_1: Some(0.5),
                cpu_pressure_avg10: Some(1.0),
                memory_pressure_avg10: Some(2.0),
                io_pressure_avg10: Some(3.0),
                zram_swap_active: true,
                is_vm_guest: false,
                workload_class: "interactive".to_string(),
                mode: "balanced".to_string(),
            },
            vec![DomainObservation {
                domain: "cpu_epp".to_string(),
                support: SupportStatus::Supported,
                mode: DomainMode::Actuate,
                gate: GateOutcome::Permitted,
                last_apply: Some(ApplyOutcome {
                    timestamp: 0,
                    action: "cpu.epp=performance (foreground responsiveness)".to_string(),
                    result: ApplyResult::Applied {
                        written_value: "performance".to_string(),
                    },
                    correlation_id: "corr".to_string(),
                }),
            }],
        );
        let json = envelope.to_json().unwrap();
        // The JSON must not contain any source file paths, line numbers,
        // or raw sysfs paths. The diagnostic surface is the boundary.
        assert!(
            !json.contains(".rs"),
            "JSON must not contain .rs file paths, got: {json}"
        );
        assert!(
            !json.contains("/sys/"),
            "JSON must not contain raw sysfs paths, got: {json}"
        );
        assert!(
            !json.contains("/proc/"),
            "JSON must not contain raw procfs paths, got: {json}"
        );
        assert!(
            !json.contains("line!"),
            "JSON must not contain line! macros, got: {json}"
        );
    }

    // ── Golden JSON test ───────────────────────────────────────────

    #[test]
    fn f3_envelope_golden_json_is_stable() {
        // A fixed golden JSON that the status surface emits. If the
        // schema changes, this test fails and the contributor must
        // update the golden JSON AND bump schema_version.
        let golden = r#"{
  "schema_version": 1,
  "timestamp": 1000,
  "correlation_id": "golden-1",
  "snapshot": {
    "on_ac": true,
    "battery_pct": 80,
    "thermal_c": 45.0,
    "loadavg_1": 0.5,
    "cpu_pressure_avg10": 1.0,
    "memory_pressure_avg10": 2.0,
    "io_pressure_avg10": 3.0,
    "zram_swap_active": true,
    "is_vm_guest": false,
    "workload_class": "interactive",
    "mode": "balanced"
  },
  "domains": [
    {
      "domain": "cpu_epp",
      "support": "supported",
      "mode": "actuate",
      "gate": "permitted",
      "last_apply": {
        "timestamp": 990,
        "action": "cpu.epp=balance_performance",
        "result": {
          "applied": {
            "written_value": "balance_performance"
          }
        },
        "correlation_id": "golden-1"
      }
    }
  ]
}"#;
        let envelope = ObservationEnvelope::from_json(golden).unwrap();
        let re_serialized = envelope.to_json().unwrap();
        // The re-serialized JSON must match the golden byte-for-byte
        // (modulo whitespace, which we normalize for comparison).
        let normalized_golden: String = golden.split_whitespace().collect();
        let normalized_actual: String = re_serialized.split_whitespace().collect();
        assert_eq!(
            normalized_golden, normalized_actual,
            "golden JSON must round-trip losslessly"
        );
    }

    // ── Provenance ─────────────────────────────────────────────────

    #[test]
    fn f3_provenance_round_trips() {
        let pv = ProvenancedValue {
            value: "60".to_string(),
            provenance: Provenance::Sysfs,
            captured_at: Some(1234567890),
        };
        let json = serde_json::to_string(&pv).unwrap();
        let restored: ProvenancedValue = serde_json::from_str(&json).unwrap();
        assert_eq!(pv, restored);
    }

    #[test]
    fn f3_provenance_optid_applied_carries_correlation_id() {
        let pv = ProvenancedValue {
            value: "performance".to_string(),
            provenance: Provenance::OptidApplied {
                correlation_id: "corr-42".to_string(),
            },
            captured_at: None,
        };
        let json = serde_json::to_string(&pv).unwrap();
        assert!(
            json.contains("corr-42"),
            "OptidApplied provenance must carry correlation_id, got: {json}"
        );
    }

    // ── SupportStatus defaults ─────────────────────────────────────

    #[test]
    fn f3_support_status_default_is_unknown() {
        assert_eq!(SupportStatus::default(), SupportStatus::Unknown);
    }

    // ── Domain coverage ────────────────────────────────────────────

    #[test]
    fn f3_envelope_for_domain_returns_none_for_unknown_domain() {
        let envelope = ObservationEnvelope::new(
            0,
            "corr".to_string(),
            SnapshotSummary {
                on_ac: None,
                battery_pct: None,
                thermal_c: None,
                loadavg_1: None,
                cpu_pressure_avg10: None,
                memory_pressure_avg10: None,
                io_pressure_avg10: None,
                zram_swap_active: false,
                is_vm_guest: false,
                workload_class: "idle".to_string(),
                mode: "auto".to_string(),
            },
            vec![],
        );
        // No domains in the envelope, so lookup returns None.
        assert!(envelope.for_domain(Domain::CpuEpp).is_none());
    }
}
