[Transfer]
Verify=true

[Source]
Type=url-file
Path=https://updates.example.invalid/adaptive/base
MatchPattern=adaptive-base_@v.raw.xz

[Target]
Type=regular-file
Path=/var/lib/adaptive/sysupdate/base
MatchPattern=adaptive-base_@v.raw
InstancesMax=3

