[Transfer]
Verify=true

[Source]
Type=url-file
Path=https://updates.rushlinux.org/base
MatchPattern=rush-linux-base_@v.raw.xz

[Target]
Type=regular-file
Path=/var/lib/rush-linux/sysupdate/base
MatchPattern=rush-linux-base_@v.raw
InstancesMax=3
