[Transfer]
Verify=true

[Source]
Type=url-file
Path=https://updates.rushlinux.org/uki
MatchPattern=rush-linux_@v+@l.efi.xz

[Target]
Type=regular-file
Path=/boot/EFI/Linux
MatchPattern=rush-linux_@v+@l.efi
InstancesMax=3
