[Transfer]
Verify=true

[Source]
Type=url-file
Path=https://updates.example.invalid/adaptive/uki
MatchPattern=adaptive-linux_@v+@l.efi.xz

[Target]
Type=regular-file
Path=/efi/EFI/Linux
MatchPattern=adaptive-linux_@v+@l.efi
InstancesMax=3

