//! Build-time codegen for the seeded hardware allowlist (WP-N4).
//!
//! Reads `data/allowlist.toml` (the compiled-in safe baseline) and emits a
//! `static SEEDED_ENTRIES: &[SeededEntry]` table plus a `SEEDED_VERSION`
//! string into `$OUT_DIR/allowlist_generated.rs`. `src/allowlist.rs` pulls it
//! in with `include!`. This is the libinput-quirks pattern (Option E in
//! docs/research/0006-hw-allowlist-db-design.md §1.7): the baseline lives in a
//! git-auditable TOML, compiles to a zero-runtime-cost `const` table, and is
//! layered under the runtime override directories at startup.
//!
//! Kept hermetic and fast: no network, no codegen crates, single file read,
//! `rerun-if-changed` scoped to the one input.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

#[derive(serde::Deserialize)]
struct AllowlistFile {
    version: String,
    #[serde(default)]
    entry: Vec<RawEntry>,
}

#[derive(serde::Deserialize)]
struct RawEntry {
    domain: String,
    hwid: String,
    #[serde(default = "default_action")]
    action: String,
    max_state: Option<u32>,
    #[serde(default)]
    tested_on: String,
    #[serde(default)]
    reason: String,
    #[serde(default)]
    verified: bool,
}

fn default_action() -> String {
    "allow".to_string()
}

fn rust_string_literal(s: &str) -> String {
    // Emit a Rust raw-ish escaped string literal. The inputs are maintainer-
    // authored TOML, but escape defensively so a stray quote or backslash can
    // never produce uncompilable generated code.
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let input = Path::new(&manifest_dir).join("data/allowlist.toml");
    println!("cargo:rerun-if-changed={}", input.display());
    println!("cargo:rerun-if-changed=build.rs");

    let text = fs::read_to_string(&input)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", input.display()));
    let parsed: AllowlistFile = toml::from_str(&text)
        .unwrap_or_else(|e| panic!("failed to parse {}: {e}", input.display()));

    let mut generated = String::new();
    writeln!(
        generated,
        "// @generated by build.rs from data/allowlist.toml — do not edit."
    )
    .unwrap();
    writeln!(
        generated,
        "pub(crate) const SEEDED_VERSION: &str = {};",
        rust_string_literal(&parsed.version)
    )
    .unwrap();
    writeln!(
        generated,
        "pub(crate) static SEEDED_ENTRIES: &[SeededEntry] = &["
    )
    .unwrap();

    for e in &parsed.entry {
        let action = match e.action.as_str() {
            "allow" => "SeededAction::Allow",
            "deny" => "SeededAction::Deny",
            other => panic!(
                "allowlist entry for {} has invalid action {other:?} (expected allow|deny)",
                e.hwid
            ),
        };
        let max_state = match e.max_state {
            Some(n) => format!("Some({n})"),
            None => "None".to_string(),
        };
        writeln!(generated, "    SeededEntry {{").unwrap();
        writeln!(
            generated,
            "        domain: {}, hwid: {},",
            rust_string_literal(&e.domain),
            rust_string_literal(&e.hwid)
        )
        .unwrap();
        writeln!(
            generated,
            "        action: {action}, max_state: {max_state},"
        )
        .unwrap();
        writeln!(
            generated,
            "        reason: {}, tested_on: {}, verified: {},",
            rust_string_literal(&e.reason),
            rust_string_literal(&e.tested_on),
            e.verified
        )
        .unwrap();
        writeln!(generated, "    }},").unwrap();
    }
    writeln!(generated, "];").unwrap();

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = Path::new(&out_dir).join("allowlist_generated.rs");
    fs::write(&out_path, generated)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", out_path.display()));
}
