[package]
name = "optid"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "optid"
path = "src/main.rs"

[dependencies]
zbus = { version = "3.14.1", features = ["blocking"] }
serde = { version = "1.0", features = ["derive"] }
