#!/usr/bin/env python3
"""Build Rush Linux edition sysexts with explicit release verity semantics."""

from __future__ import annotations

import importlib.util
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

_IMPL_PATH = Path(__file__).with_name("_edition_sysext_impl.py")
_IMPL_NAME = f"{__name__.replace('-', '_')}_implementation"
_SPEC = importlib.util.spec_from_file_location(_IMPL_NAME, _IMPL_PATH)
if _SPEC is None or _SPEC.loader is None:
    raise RuntimeError(f"cannot load edition sysext implementation: {_IMPL_PATH}")
_IMPL = importlib.util.module_from_spec(_SPEC)
sys.modules[_SPEC.name] = _IMPL
_SPEC.loader.exec_module(_IMPL)

for _name in dir(_IMPL):
    if not _name.startswith("__"):
        globals()[_name] = getattr(_IMPL, _name)

# Keep dynamically exported types visible to static analysis as well.
EditionError = _IMPL.EditionError

_ORIGINAL_PREPARE_WORKSPACE = _IMPL.prepare_workspace
_ORIGINAL_RUN_BUILD = _IMPL.run_build


def render_shared_config(
    *,
    verity: str = "auto",
    workspace_directory: Path | None = None,
) -> str:
    if verity not in {"auto", "signed", "no"}:
        raise EditionError(f"unsupported mkosi verity mode: {verity!r}")
    workspace_setting = ""
    if workspace_directory is not None:
        workspace_setting = f"WorkspaceDirectory={workspace_directory.resolve()}\n"
    return f"""# Generated by tools/build-edition-sysext.py; do not edit.
[Distribution]
Distribution=arch

[Output]
Format=none
OutputDirectory=output

[Build]
CacheDirectory=cache
{workspace_setting}
[Validation]
Verity={verity}
"""


def render_image_config(plan: dict[str, Any]) -> str:
    packages = "\n".join(f"    {item}" for item in plan["packages"]["sysext"])
    extension_id = plan["extension"]["id"]
    filename = plan["extension"]["filename"]
    return f"""# Generated by tools/build-edition-sysext.py; do not edit.
[Output]
Format=sysext
Overlay=yes
ImageId={extension_id}
Output={filename}

[Content]
BaseTrees=../../base
ExtraTrees=../../tree
CleanPackageMetadata=no
Packages=
{packages}
"""


def _materialize_disk_base(image: Path, target: Path) -> None:
    command = [
        "systemd-dissect",
        "--read-only",
        "--copy-from",
        str(image),
        "/",
        str(target),
    ]
    try:
        result = subprocess.run(command, text=True, check=False)
    except OSError as exc:
        raise EditionError(f"cannot execute systemd-dissect: {exc}") from exc
    if result.returncode != 0:
        raise EditionError(
            "cannot materialize common base image as a directory for mkosi BaseTrees; "
            f"systemd-dissect exited with status {result.returncode}"
        )


def prepare_workspace(
    *,
    plan: dict[str, Any],
    workspace: Path,
    base_tree: Path,
    force: bool,
) -> None:
    """Prepare a sysext workspace with a directory-form BaseTrees lower layer.

    mkosi's supported sysext pattern uses a directory base with Overlay=yes.
    A bootable raw Rush base is therefore copied out read-only before entering
    mkosi's build sandbox. Directory callers remain zero-copy via the original
    symlink path.
    """
    base_tree = base_tree.resolve()
    if base_tree.is_dir():
        _ORIGINAL_PREPARE_WORKSPACE(
            plan=plan,
            workspace=workspace,
            base_tree=base_tree,
            force=force,
        )
        return
    if not base_tree.is_file():
        raise EditionError(f"base tree/image does not exist: {base_tree}")

    workspace = workspace.resolve()
    workspace.parent.mkdir(parents=True, exist_ok=True)
    materialized = Path(
        tempfile.mkdtemp(prefix=f".{workspace.name}-base-", dir=workspace.parent)
    )
    try:
        _materialize_disk_base(base_tree, materialized)
        _ORIGINAL_PREPARE_WORKSPACE(
            plan=plan,
            workspace=workspace,
            base_tree=materialized,
            force=force,
        )

        base_link = workspace / "base"
        if not base_link.is_symlink():
            raise EditionError(
                f"prepared workspace base is not the expected symlink: {base_link}"
            )
        base_link.unlink()
        os.replace(materialized, base_link)
    except Exception:
        shutil.rmtree(materialized, ignore_errors=True)
        raise


def run_build(
    *,
    workspace: Path,
    plan: dict[str, Any],
    mkosi: str,
    key: Path | None,
    certificate: Path | None,
    unsigned_development: bool,
) -> Path:
    if key is not None and unsigned_development:
        raise EditionError(
            "--unsigned-development cannot be combined with signing credentials"
        )
    if (key is None) != (certificate is None):
        raise EditionError("--key and --certificate must be supplied together")
    if key is None and not unsigned_development:
        raise EditionError(
            "release builds require --key and --certificate; "
            "use --unsigned-development only for local non-release builds"
        )

    workspace = workspace.resolve()
    verity_mode = "signed" if key is not None else "no"
    # mkosi forbids WorkspaceDirectory= beneath any source directory. Keep the
    # overlay workspace as a sibling of the generated source tree so CI still
    # uses the host-backed checkout filesystem instead of Docker /var/tmp.
    mkosi_workspace = (
        workspace.parent / f".{workspace.name}-mkosi-workspace"
    ).resolve()
    mkosi_workspace.mkdir(parents=True, exist_ok=True)
    (workspace / "mkosi.conf").write_text(
        render_shared_config(
            verity=verity_mode,
            workspace_directory=mkosi_workspace,
        ),
        encoding="utf-8",
    )
    artifact = _ORIGINAL_RUN_BUILD(
        workspace=workspace,
        plan=plan,
        mkosi=mkosi,
        key=key,
        certificate=certificate,
        unsigned_development=unsigned_development,
    )

    receipt_path = workspace / "output" / f"{plan['extension']['id']}.build.json"
    try:
        receipt = json.loads(receipt_path.read_text(encoding="utf-8"))
        if not isinstance(receipt, dict):
            raise ValueError("receipt is not a JSON object")
        receipt["signed"] = verity_mode == "signed"
        receipt["verity"] = verity_mode
        _IMPL.write_json(receipt_path, receipt)
    except (OSError, UnicodeDecodeError, json.JSONDecodeError, ValueError) as exc:
        receipt_path.unlink(missing_ok=True)
        raise EditionError(
            f"cannot record sysext verity mode in build receipt: {exc}"
        ) from exc
    return artifact


# The implementation functions resolve these names through their module globals.
# Override the public surfaces so prepare/build share one mkosi-26-compatible
# directory-base contract even when the caller supplies a bootable raw image.
_IMPL.render_shared_config = render_shared_config
_IMPL.render_image_config = render_image_config
_IMPL.prepare_workspace = prepare_workspace
_IMPL.run_build = run_build


if __name__ == "__main__":
    raise SystemExit(_IMPL.main())
