#!/usr/bin/env python3
"""Build Rush Linux edition sysexts with explicit release verity semantics."""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path
from typing import Any

_IMPL_PATH = Path(__file__).with_name("edition_sysext_impl.py")
_IMPL_NAME = f"{__name__.replace('-', '_')}_implementation"
_SPEC = importlib.util.spec_from_file_location(_IMPL_NAME, _IMPL_PATH)
if _SPEC is None or _SPEC.loader is None:
    raise RuntimeError(f"cannot load edition sysext implementation: {_IMPL_PATH}")
_IMPL = importlib.util.module_from_spec(_SPEC)
sys.modules[_SPEC.name] = _IMPL
_SPEC.loader.exec_module(_IMPL)

for _name in dir(_IMPL):
    if not _name.startswith("__"):
        globals()[_name] = getattr(_IMPL, _name)

_ORIGINAL_RUN_BUILD = _IMPL.run_build


def render_shared_config(*, verity: str = "auto") -> str:
    if verity not in {"auto", "signed", "no"}:
        raise EditionError(f"unsupported mkosi verity mode: {verity!r}")
    return f"""# Generated by tools/build-edition-sysext.py; do not edit.
[Output]
Format=none
OutputDirectory=output
CacheDirectory=cache

[Validation]
Verity={verity}
"""


def run_build(
    *,
    workspace: Path,
    plan: dict[str, Any],
    mkosi: str,
    key: Path | None,
    certificate: Path | None,
    unsigned_development: bool,
) -> Path:
    if key is not None and unsigned_development:
        raise EditionError(
            "--unsigned-development cannot be combined with signing credentials"
        )
    if (key is None) != (certificate is None):
        raise EditionError("--key and --certificate must be supplied together")
    if key is None and not unsigned_development:
        raise EditionError(
            "release builds require --key and --certificate; "
            "use --unsigned-development only for local non-release builds"
        )

    verity_mode = "signed" if key is not None else "no"
    (workspace / "mkosi.conf").write_text(
        render_shared_config(verity=verity_mode),
        encoding="utf-8",
    )
    artifact = _ORIGINAL_RUN_BUILD(
        workspace=workspace,
        plan=plan,
        mkosi=mkosi,
        key=key,
        certificate=certificate,
        unsigned_development=unsigned_development,
    )

    receipt_path = workspace / "output" / f"{plan['extension']['id']}.build.json"
    try:
        receipt = json.loads(receipt_path.read_text(encoding="utf-8"))
        if not isinstance(receipt, dict):
            raise ValueError("receipt is not a JSON object")
        receipt["signed"] = verity_mode == "signed"
        receipt["verity"] = verity_mode
        _IMPL.write_json(receipt_path, receipt)
    except (OSError, UnicodeDecodeError, json.JSONDecodeError, ValueError) as exc:
        receipt_path.unlink(missing_ok=True)
        raise EditionError(
            f"cannot record sysext verity mode in build receipt: {exc}"
        ) from exc
    return artifact


_IMPL.render_shared_config = render_shared_config
_IMPL.run_build = run_build


if __name__ == "__main__":
    raise SystemExit(_IMPL.main())
